#SOURCE CODE FOR MOVIE TICKET BOOKING

print("**********************************************************************************************************************************************")
print("**                                                                                                                                          **")
print("**                                                WELCOME TO PALLAVAN THEATRE                                                               **")
print("**                                                                                                                                          **")
print("**********************************************************************************************************************************************")
print()
print()

#CREATING DATABASE
import mysql.connector
import datetime
import matplotlib.pyplot as pl
mydb=mysql.connector.connect(host="localhost",user="root",passwd="admin")
mycursor=mydb.cursor()
mycursor.execute("create database if not exists MOVIE")
mycursor.execute("use MOVIE")

#CREATING REQUIRED TABLES
mycursor.execute("create table if not exists SD3D(name varchar(50) not null,ph_no bigint not null,t_tickets int(15) not null,gender varchar(20) not null,seat_type varchar(87),grand_total varchar(90),status varchar (90))")
mycursor.execute("create table if not exists BAAGHI_3(name varchar(50) not null,ph_no bigint not null,t_tickets int(15) not null,gender varchar(20) not null,seat_type varchar(87),grand_total varchar(90),status varchar (90))")
mycursor.execute("create table if not exists CHHAPAAK(name varchar(50) not null,ph_no bigint not null,t_tickets int(15) not null,gender varchar(20) not null,seat_type varchar(87),grand_total varchar(90),status varchar (90))")
mydb.commit()
while(True):
    print("**                                                                                                                                          **")
    print("______________________________________________________________________________________________________________________________________________")
    print("                                                            1=STREET DANCER 3D                                                                ")
    print("                                                            2=BAAGHI 3                                                                        ")
    print("                                                            3=CHHAPAAK                                                                        ")
    print("                                                            4=MOVIE RATINGS                                                                   ")
    print("                                                            5=EXIT                                                                            ")
    print("______________________________________________________________________________________________________________________________________________")
    print("**                                                                                                                                          **")
    ch=int(input("                Enter your choice:"))
    
#PROCEDURE FOR TICKET BOOKING
    if(ch==1):
           name=str(input("                Enter your full name:"))
           ph_no=int(input("                Enter your phone number:"))
           t_tickets=int(input("                Enter total no. of tickets:"))
           gender=str(input("                Enter your gender(M/F):"))

           print("______________________________________________________________________________________________________________________________________________")
           print("**                                                 PLEASE ENTER YOUR SEAT TYPE                                                              **")
           print("**                                                 1=NORMAL SEATING(Rs.200)                                                                 **")
           print("**                                                 2=PREMIUM GLIDER SEATING(Rs.400)                                                         **")
           print("**                                                 3=SUPREME CHAIR LOUNGE(Rs.700)                                                           **")
           print("______________________________________________________________________________________________________________________________________________")
           print("")
           choose=int(input("                Choose your seat type:"))
           print("")
           if(choose==1):
               g_total=t_tickets*200
               mycursor.execute("insert into SD3D values('"+name+"','"+str(ph_no)+"','"+str(t_tickets)+"','"+gender+"','"+"normal seating"+"','"+str(g_total)+"','"+"booked"+"')")
               mydb.commit()
               now=datetime.datetime.now()
               dtm=str(now)
               print("-"*150)
               print("\t\t\t\t\t\t\tINVOICE")
               print("\t\t\t\t\tSTREET DANCER 3D\t(NORMAL SEATING)")
               print("-"*150)
               print()
               print("Date:{0:>150s}".format(dtm))
               print("-"*150)
               print("NAME\t\t\tPHONE NO\t\tGENDER\t\tTOTAL TICKETS\t\tGRAND TOTAL")
               print("-"*150)
               print("{0:<25s}".format(name),end="")
               print("{0:<25d}".format(ph_no),end="")
               print("{0:>3s}".format(gender),end="")
               print("{0:>20d}".format(t_tickets),end="")
               print("{0:>25d}".format(g_total))
               print("-"*150)
               print("                YOU CAN PAY YOUR AMOUNT VIA NET BANKING OR PAYTM")
               print("########                                       THANK YOU FOR VISITING PALLAVAN THEATRE                                                ########")
               print("                PLEASE RATE YOUR EXPERIENCE OF ONLINE MOVIE TICKET BOOKING   :)")
               rate=int(input("                Rate us out of 5:"))
               print("**********************************************************************************************************************************************")
               print()
               
           elif(choose==2):
               g_total=t_tickets*400
               mycursor.execute("insert into SD3D values('"+name+"','"+str(ph_no)+"','"+str(t_tickets)+"','"+gender+"','"+"premium glider seating"+"','"+str(g_total)+"','"+"booked"+"')")
               mydb.commit()
               now=datetime.datetime.now()
               dtm=str(now)
               print("-"*150)
               print("\t\t\t\t\t\t\tINVOICE")
               print("\t\t\t\t\tSTREET DANCER 3D\t(PREMIUM GLIDER SEATING)")
               print("-"*150)
               print()
               print("Date:{0:>150s}".format(dtm))
               print("-"*150)
               print("NAME\t\t\tPHONE NO\t\tGENDER\t\tTOTAL TICKETS\t\tGRAND TOTAL")
               print("-"*150)
               print("{0:<25s}".format(name),end="")
               print("{0:<25d}".format(ph_no),end="")
               print("{0:>3s}".format(gender),end="")
               print("{0:>20d}".format(t_tickets),end="")
               print("{0:>25d}".format(g_total))
               print("-"*150)
               print("                YOU CAN PAY YOUR AMOUNT VIA NET BANKING OR PAYTM")
               print("########                                       THANK YOU FOR VISITING PALLAVAN THEATRE                                                ########")
               print("                PLEASE RATE YOUR EXPERIENCE OF ONLINE MOVIE TICKET BOOKING   :)")
               rate=int(input("                Rate us out of 5:"))
               print("**********************************************************************************************************************************************")
               print()
               
           elif(choose==3):
               g_total=t_tickets*700
               mycursor.execute("insert into SD3D values('"+name+"','"+str(ph_no)+"','"+str(t_tickets)+"','"+gender+"','"+"supreme chair lounge"+"','"+str(g_total)+"','"+"booked"+"')")
               mydb.commit()
               now=datetime.datetime.now()
               dtm=str(now)
               print("-"*150)
               print("\t\t\t\t\t\t\tINVOICE")
               print("\t\t\t\t\tSTREET DANCER 3D\t(SUPREME CHAIR LOUNGE)")
               print("-"*150)
               print()
               print("Date:{0:>150s}".format(dtm))
               print("-"*150)
               print("NAME\t\t\tPHONE NO\t\tGENDER\t\tTOTAL TICKETS\t\tGRAND TOTAL")
               print("-"*150)
               print("{0:<25s}".format(name),end="")
               print("{0:<25d}".format(ph_no),end="")
               print("{0:>3s}".format(gender),end="")
               print("{0:>20d}".format(t_tickets),end="")
               print("{0:>25d}".format(g_total))
               print("-"*150)
               print("                YOU CAN PAY YOUR AMOUNT VIA NET BANKING OR PAYTM")
               print("########                                       THANK YOU FOR VISITING PALLAVAN THEATRE                                                ########")
               print("                PLEASE RATE YOUR EXPERIENCE OF ONLINE MOVIE TICKET BOOKING   :)")
               rate=int(input("                Rate us out of 5:"))
               print("**********************************************************************************************************************************************")
               print()
               
           else:
               print("                YOU HAVE TO CHOOSE BETWEEN 1,2,3")
                     

#BAAGHI 3
    elif(ch==2):
        name=str(input("                Enter your full name:"))
        ph_no=int(input("                Enter your phone number:"))
        t_tickets=int(input("                Enter total no. of tickets:"))
        gender=str(input("                Enter your gender(M/F):"))

        print("______________________________________________________________________________________________________________________________________________")
        print("**                                                 PLEASE ENTER YOUR SEAT TYPE                                                              **")
        print("**                                                 1=NORMAL SEATING(Rs.200)                                                                 **")
        print("**                                                 2=PREMIUM GLIDER SEATING(Rs.400)                                                         **")
        print("**                                                 3=SUPREME CHAIR LOUNGE(Rs.700)                                                           **")
        print("______________________________________________________________________________________________________________________________________________")
        print("")
        choose=int(input("                choose your seat type:"))
        print("")
               
        if(choose==1):
            g_total=t_tickets*200
            mycursor.execute("insert into BAAGHI_3 values('"+name+"','"+str(ph_no)+"','"+str(t_tickets)+"','"+gender+"','"+"normal seating"+"','"+str(g_total)+"','"+"booked"+"')")
            mydb.commit()
            now=datetime.datetime.now()
            dtm=str(now)
            print("-"*150)
            print("\t\t\t\t\t\t\tINVOICE")
            print("\t\t\t\t\BAAGHI 3\t(NORMAL SEATING)")
            print("-"*150)
            print()
            print("Date:{0:>150s}".format(dtm))
            print("-"*150)
            print("NAME\t\t\tPHONE NO\t\tGENDER\t\tTOTAL TICKETS\t\tGRAND TOTAL")
            print("-"*150)
            print("{0:<25s}".format(name),end="")
            print("{0:<25d}".format(ph_no),end="")
            print("{0:>3s}".format(gender),end="")
            print("{0:>20d}".format(t_tickets),end="")
            print("{0:>25d}".format(g_total))
            print("-"*150)
            print("                YOU CAN PAY YOUR AMOUNT VIA NET BANKING OR PAYTM")
            print("########                                       THANK YOU FOR VISITING PALLAVAN THEATRE                                                ########")
            print("                PLEASE RATE YOUR EXPERIENCE OF ONLINE MOVIE TICKET BOOKING   :)")
            rate=int(input("                Rate us out of 5:"))
            print("**********************************************************************************************************************************************")
            print()
            
        elif(choose==2):
            g_total=t_tickets*400
            mycursor.execute("insert into BAAGHI_3 values('"+name+"','"+str(ph_no)+"','"+str(t_tickets)+"','"+gender+"','"+"premium glider seating"+"','"+str(g_total)+"','"+"booked"+"')")
            mydb.commit()
            now=datetime.datetime.now()
            dtm=str(now)
            print("-"*150)
            print("\t\t\t\t\t\t\tINVOICE")
            print("\t\t\t\t\tBAAGHI 3\t(PREMIUM GLIDER SEATING)")
            print("-"*150)
            print()
            print("Date:{0:>150s}".format(dtm))
            print("-"*150)
            print("NAME\t\t\tPHONE NO\t\tGENDER\t\tTOTAL TICKETS\t\tGRAND TOTAL")
            print("-"*150)
            print("{0:<25s}".format(name),end="")
            print("{0:<25d}".format(ph_no),end="")
            print("{0:>3s}".format(gender),end="")
            print("{0:>20d}".format(t_tickets),end="")
            print("{0:>25d}".format(g_total))
            print("-"*150)
            print("                YOU CAN PAY YOUR AMOUNT VIA NET BANKING OR PAYTM")
            print("########                                       THANK YOU FOR VISITING PALLAVAN THEATRE                                                ########")
            print("                PLEASE RATE YOUR EXPERIENCE OF ONLINE MOVIE TICKET BOOKING   :)")
            rate=int(input("                Rate us out of 5:"))
            print("**********************************************************************************************************************************************")
            print()
            
        elif(choose==3):
            g_total=t_tickets*700
            mycursor.execute("insert into BAAGHI_3 values('"+name+"','"+str(ph_no)+"','"+str(t_tickets)+"','"+gender+"','"+"supreme chair lounge"+"','"+str(g_total)+"','"+"booked"+"')")
            mydb.commit()
            now=datetime.datetime.now()
            dtm=str(now)
            print("-"*150)
            print("\t\t\t\t\t\t\tINVOICE")
            print("\t\t\t\t\tBAAGHI 3\t(SUPREME CHAIR LOUNGE)")
            print("-"*150)
            print()
            print("Date:{0:>150s}".format(dtm))
            print("-"*150)
            print("NAME\t\t\tPHONE NO\t\tGENDER\t\tTOTAL TICKETS\t\tGRAND TOTAL")
            print("-"*150)
            print("{0:<25s}".format(name),end="")
            print("{0:<25d}".format(ph_no),end="")
            print("{0:>3s}".format(gender),end="")
            print("{0:>20d}".format(t_tickets),end="")
            print("{0:>25d}".format(g_total))
            print("-"*150)
            print("                YOU CAN PAY YOUR AMOUNT VIA NET BANKING OR PAYTM")
            print("########                                       THANK YOU FOR VISITING PALLAVAN THEATRE                                                ########")
            print("                PLEASE RATE YOUR EXPERIENCE OF ONLINE MOVIE TICKET BOOKING   :)")
            rate=int(input("                Rate us out of 5:"))
            print("**********************************************************************************************************************************************")
            print()
            
        else:
            print("                YOU HAVE TO CHOOSE BETWEEN 1,2,3")


#CHHAPAAK
    elif(ch==3):
        name=str(input("                Enter your full name:"))
        ph_no=int(input("                Enter your phone number:"))
        t_tickets=int(input("                Enter total no. of tickets:"))
        gender=str(input("                Enter your gender(M/F):"))

        print("______________________________________________________________________________________________________________________________________________")
        print("**                                                 PLEASE ENTER YOUR SEAT TYPE                                                              **")
        print("**                                                 1=NORMAL SEATING(Rs.200)                                                                 **")
        print("**                                                 2=PREMIUM GLIDER SEATING(Rs.400)                                                         **")
        print("**                                                 3=SUPREME CHAIR LOUNGE(Rs.700)                                                           **")
        print("______________________________________________________________________________________________________________________________________________")
        print("")
        choose=int(input("                   choose your seat type:"))
        print("")
        
        if(choose==1):
            g_total=t_tickets*200
            mycursor.execute("insert into CHHAPAAK values('"+name+"','"+str(ph_no)+"','"+str(t_tickets)+"','"+gender+"','"+"normal seating"+"','"+str(g_total)+"','"+"booked"+"')")
            mydb.commit()
            now=datetime.datetime.now()
            dtm=str(now)
            print("-"*150)
            print("\t\t\t\t\t\t\tINVOICE")
            print("\t\t\t\t\tCHHAPAAK\t(NORMAL SEATING)")
            print("-"*150)
            print()
            print("Date:{0:>150s}".format(dtm))
            print("-"*150)
            print("NAME\t\t\tPHONE NO\t\tGENDER\t\tTOTAL TICKETS\t\tGRAND TOTAL")
            print("-"*150)
            print("{0:<25s}".format(name),end="")
            print("{0:<25d}".format(ph_no),end="")
            print("{0:>3s}".format(gender),end="")
            print("{0:>20d}".format(t_tickets),end="")
            print("{0:>25d}".format(g_total))
            print("-"*150)
            print("                YOU CAN PAY YOUR AMOUNT VIA NET BANKING OR PAYTM")
            print("########                                       THANK YOU FOR VISITING PALLAVAN THEATRE                                                ########")         
            print("                PLEASE RATE YOUR EXPERIENCE OF ONLINE MOVIE TICKET BOOKING   :)")
            rate=int(input("                Rate us out of 5:"))
            print("**********************************************************************************************************************************************")
            print()
            
        elif(choose==2):
            g_total=t_tickets*400
            mycursor.execute("insert into CHHAPAAK values('"+name+"','"+str(ph_no)+"','"+str(t_tickets)+"','"+gender+"','"+"premium glider seating"+"','"+str(g_total)+"','"+"booked"+"')")
            mydb.commit()
            now=datetime.datetime.now()
            dtm=str(now)
            print("-"*150)
            print("\t\t\t\t\t\t\tINVOICE")
            print("\t\t\t\t\tCHHAPAAK\t(PREMIUM GLIDER SEATING)")
            print("-"*150)
            print()
            print("Date:{0:>150s}".format(dtm))
            print("-"*150)
            print("NAME\t\t\tPHONE NO\t\tGENDER\t\tTOTAL TICKETS\t\tGRAND TOTAL")
            print("-"*150)
            print("{0:<25s}".format(name),end="")
            print("{0:<25d}".format(ph_no),end="")
            print("{0:>3s}".format(gender),end="")
            print("{0:>20d}".format(t_tickets),end="")
            print("{0:>25d}".format(g_total))
            print("-"*150)
            print("                YOU CAN PAY YOUR AMOUNT VIA NET BANKING OR PAYTM")
            print("########                                       THANK YOU FOR VISITING PALLAVAN THEATRE                                                ########")                
            print("                PLEASE RATE YOUR EXPERIENCE OF ONLINE MOVIE TICKET BOOKING   :)")
            rate=int(input("                Rate us out of 5:"))
            print("**********************************************************************************************************************************************")
            print()
            
        elif(choose==3):
            g_total=t_tickets*700
            mycursor.execute("insert into CHHAPAAK values('"+name+"','"+str(ph_no)+"','"+str(t_tickets)+"','"+gender+"','"+"supreme chair lounge"+"','"+str(g_total)+"','"+"booked"+"')")
            mydb.commit()
            now=datetime.datetime.now()
            dtm=str(now)
            print("-"*150)
            print("\t\t\t\t\t\t\tINVOICE")
            print("\t\t\t\t\tCHHAPAAK\t(SUPREME CHAIR LOUNGE)")
            print("-"*150)
            print()
            print("Date:{0:>150s}".format(dtm))
            print("-"*150)
            print("NAME\t\t\tPHONE NO\t\tGENDER\t\tTOTAL TICKETS\t\tGRAND TOTAL")
            print("-"*150)
            print("{0:<25s}".format(name),end="")
            print("{0:<25d}".format(ph_no),end="")
            print("{0:>3s}".format(gender),end="")
            print("{0:>20d}".format(t_tickets),end="")
            print("{0:>25d}".format(g_total))
            print("-"*150)
            print("                YOU CAN PAY YOUR AMOUNT VIA NET BANKING OR PAYTM")
            print("########                                       THANK YOU FOR VISITING PALLAVAN THEATRE                                                ########")
            print("                PLEASE RATE YOUR EXPERIENCE OF ONLINE MOVIE TICKET BOOKING   :)")
            rate=int(input("                Rate us out of 5:"))
            print("**********************************************************************************************************************************************")
            print()
            
        else:
            print("                YOU HAVE TO CHOOSE BETWEEN 1,2,3")            
               
    elif(ch==4):
        movie=["STREET DANCER 3D","BAAGHI 3","CHHAPAAK"]
        ratings=[3.6,3,4.8]
        pl.bar(movie,ratings,color=["gold"])
        pl.title("******MOVIE RATINGS******")
        pl.xlabel("Movies")
        pl.ylabel("Ratings")
        pl.show()
        
    elif(ch==5):
        print("########                                       THANK YOU FOR VISITING PALLAVAN THEATRE                                                ########")
        break    
        
print("**                                                                                                                                          **")
print("**********************************************************************************************************************************************")
print("**********************************************************************************************************************************************")
                
   

        


           
    
